---
title: "Reservoir Gradient: Microbial Communities"
author: "Jay T. Lennon, Megan L. Larsen, Mario E. Muscarella"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

Project looking at microbial composition and processes along a reservoir gradient

# Initial Setup
```{r}
rm(list=ls())
setwd("~/GitHub/ReservoirGradient")
source("./bin/MothurTools.R")
require("vegan")
se <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}
```

# Import Shared and Design Files
```{r}
# Define Inputs
# Design = general design file for experiment
# shared = OTU table from mothur with sequence similarity clustering
# Taxonomy = Taxonomic information for each OTU
design <- "./data/UL.design.txt"
shared <- "./data/UL.bac.final.shared"
taxon  <- "./data/UL.bac.final.0.03.taxonomy"

# Import Design
design <- read.delim(design, header=T, row.names=1)

# Import Shared Files
OTUs <- read.otu(shared = shared, cutoff = "0.03")         # 97% Similarity

# Import Taxonomy
OTU.tax <- read.tax(taxonomy = taxon, format = "rdp")
```

# Data Transormations
```{r}
# Remove OTUs with less than two occurances across all sites
OTUs <- OTUs[, which(colSums(OTUs) >= 2)]

# Make Relative Abundence Matrices
OTUsREL <- OTUs
for(i in 1:dim(OTUs)[1]){
  OTUsREL[i,]<- OTUs[i,]/sum(OTUs[i,])
}

# Log Transform Relative Abundances
OTUsREL.log <- decostand(OTUs, method="log")

# Remove Low Coverage Samples
coverage <- rowSums(OTUs)

```



# Calculate Alpha Diversity
```{r}
# Observed Richness
S.obs <- rowSums((OTUs > 0) * 1)

# Good's Coverage
C <- function(x = ""){
  1 - (sum(x == 1) / rowSums(x))
}
C(OTUs)

# Simpson's Evenness
SimpE <- function(x = ""){
  x <- as.data.frame(x)
  D <- diversity(x, "inv")
  S <- sum((x > 0) * 1) 
  E <- (D)/S 
  return(E)
}
simpsE <- round(apply(OTUs, 1, SimpE), 3)

# Diversity
H <- function(x = ""){
  x <- x[x>0]
  H = 0
  for (n_i in x){
    p = n_i / sum(x)
    H = H - p*log(p) 
  }
  return(H)
}

shan <- round(apply(OTUs, 1, H), 2)
diversity(OTUs, index = "shannon")

alpha.div <- cbind(design, S.obs, simpsE, shan)


```


# Alpha Diversity Plots
```{r}
# Seperate data based on lake and soil samples
lake <- alpha.div[-c(1:3),]
soil <- alpha.div[c(1:3), ]

# Richness across Reservoir Gradient
opar <- par()
par(mar = c(5,6, 1, 1))
mol <- rep(NA, length(lake$molecule))
  for (i in 1:length(mol)){
    if (lake$molecule[i] == "DNA"){
      mol[i] <- 21
    } else {
      mol[i] <- 24
    }
  }
cols <- rep(NA, length(lake$molecule))
  for (i in 1:length(cols)){
    if (lake$molecule[i] == "DNA"){
      cols[i] <- "gray15"
    } else {
      cols[i] <- "gray75"
    }
  }

plot(lake$S.obs ~ lake$distance, col= "black", bg = cols, pch=mol, las = 1,
     xlim = c(0,400), ylim = c(0, 2750), cex = 1.5, 
     xlab="", ylab="")

axis(side = 1, lwd.ticks = 2, cex.axis = 1, las = 1)
axis(side = 2, lwd.ticks = 2, cex.axis = 1, las = 1)
axis(side = 3, lwd.ticks = 2, tck=-0.01, labels = F,  cex.axis = 2, las = 1)                              
axis(side = 4, lwd.ticks = 2, tck=-0.01, labels = F,  cex.axis = 2, las = 1)
axis(side = 1, lwd.ticks = 2, tck=0.01, labels = F,  cex.axis = 2, las = 1)                              
axis(side = 2, lwd.ticks = 2, tck=0.01, labels = F,  cex.axis = 2, las = 1)
axis(side = 3, lwd.ticks = 2, tck=0.01, labels = F,  cex.axis = 2, las = 1)                              
axis(side = 4, lwd.ticks = 2, tck=0.01, labels = F,  cex.axis = 2, las = 1)

mtext("Distance from Dam (m)" , side = 1, line = 3, cex=1.5)
mtext("Observed Richness (S)" , side = 2, line = 4, cex=1.5)

box(lwd=2)

legend("topleft", legend = levels(lake$molecule), pch=c(21, 24), 
       pt.bg = c("gray15", "gray75"), bty='n', cex = 1.25)

abline(h = mean(soil$S.obs), lty=2, col="blue")

mean(soil$S.obs)


# S
plot(lake$shan ~ lake$distance, col=lake$molecule, pch=19,
     xlab="Distance from Dam (m)", ylab="Shannon's Diversity (H)")
legend("topleft", legend = levels(lake$molecule), col=c(1,2), pch=19, bty='n')




```


# Beta Diversity
```{r}
# Calculate Bray-Curtis 
UL.db <- vegdist(OTUsREL, method = "bray")

UL.pcoa <- cmdscale(UL.db, eig = TRUE, k = 3) 

explainvar1 <- round(UL.pcoa$eig[1] / sum(UL.pcoa$eig), 3) * 100
explainvar2 <- round(UL.pcoa$eig[2] / sum(UL.pcoa$eig), 3) * 100
explainvar3 <- round(UL.pcoa$eig[3] / sum(UL.pcoa$eig), 3) * 100
sum.eig <- sum(explainvar1, explainvar2, explainvar3)

# Define Plot Parameters
par(mar = c(5, 5, 1, 2) + 0.1)

# Initiate Plot
plot(UL.pcoa$points[ ,1], UL.pcoa$points[ ,2], ylim = c(-0.8, 0.8),
     xlab = paste("PCoA 1 (", explainvar1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", explainvar2, "%)", sep = ""),
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = FALSE)

# Add Axes
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

# Add Points & Labels
points(UL.pcoa$points[ ,1], UL.pcoa$points[ ,2],
       pch = 19, cex = 3, bg = "gray", col = "gray")
text(UL.pcoa$points[ ,1], UL.pcoa$points[ ,2], 
     labels = row.names(UL.pcoa$points))

# Add Points & Labels
points(UL.pcoa$points[ ,1], UL.pcoa$points[ ,2],
       pch = 19, cex = 3, bg = "gray", col = design$molecule)
text(UL.pcoa$points[ ,1], UL.pcoa$points[ ,2], 
     labels = row.names(UL.pcoa$points))

```














