---
title: "Reservoir Gradient -- nutrient resource maps"
author: "Megan L. Larsen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

Project looking at microbial composition and processes along a reservoir gradient

```{r}
rm(list=ls())
getwd()
setwd("C:/Users/Megan/Github/ReservoirGradient")
```

## FIGURES: NUTRIENT PATTERNS ACROSS RESERVOIR
```{r}
require(ggplot2); require(ggmap)
require(reshape); require(plyr)
require(rgdal); require(maptools)
require(raster); require(akima)
require(OpenMx);require(grid)

# Load environmental data
env.dat <- read.csv("./data/ResGrad_EnvDat.csv", header = TRUE)
env.dat <- env.dat[-16,]
```

```{r example}
env.mat <- vec2diag(env.dat$TP)
rownames(env.mat) <- env.dat$long
colnames(env.mat) <- env.dat$lat
env.mat[env.mat == 0] <- 1
m1 <- melt(env.mat)
colnames(m1) <- c("lon","lat","TP")

cols <- c(2,3,10)
test <- env.dat[,cols]

# Import University Lake Polygon
ul <- readOGR("./maps","UniversityLakePoly")
ul.dat <- readOGR("./maps","UniversityLake")
summary(ul) # Check projection and and datum
#ul <- spTransform(ul, CRS("+proj=longlat +datum=WGS84")) # transform if necessary
ul <- fortify(ul) # raster image for plotting with ggplot2

ul.coords <- c(lon = -86.503087, lat = 39.188686)

# using google maps as base
ul.map <- get_map(location = ul.coords, 
                  zoom = 17, maptype = "terrain", 
                  source = "google", messaging = F, color = "bw")
base.map <- ggmap(ul.map, extent = "device", legend = "topleft")


# base plot
p <- ggplot(aes(long,lat), data = env.dat) + 
  geom_polygon(fill = "grey", size = 1, color = 'black', data = ul, alpha = 1) +
  labs(x = "Longitude", y = "Latitude") +
  theme(#plot.margin = unit(c(1, 6, 1, 6), "cm"),
        panel.background = element_rect(fill = "white"),
        #panel.margin = unit(1,1,1,1),
        #panel.grid.major = element_line(colour = "white"),
        #panel.grid.minor = element_line(colour = "white"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 20, face = "bold"),
        legend.position = c(0.9,0.25))

TP <- p +  
  geom_point(aes(size = TP)) + 
  scale_size(name="Total Phosphorus\n(ug P/L)")
print(TP)

DO <- p +  
  geom_point(aes(size = DO)) + 
  scale_size(name="Dissolved Oxygen\n(mg/L)")
print(DO)

chla <- p +  
  geom_point(aes(size = chla)) + 
  scale_size(name="Chlorophyll a\n(mg/L)")
print(chla)

pH <- p +  
  geom_point(aes(size = pH)) + 
  scale_size(name="pH")

print(pH)

color <- p +  
  geom_point(aes(size = color)) + 
  scale_size(name="Abs 440 nm")
print(color)

grid.arrange(TP,chla,color,pH,color,nrow=2,ncol=3)
```
